### ISSUE TITLE
Change typing for `DataLoader`: type 'ReactNode' is not a valid JSX element.

### ISSUE THREAD

**Issue by arteria32** [gravity-ui/data-source#20]
I caught an error in DataLoader when using it as you describe in the README.
Let's change a typing for `DataLoader` from `ReactNode` to `JSX.Element` or `ComponentType`. I think it is the right way to define a React component.

If you agree with me, I can help with PR.

**Steps to reproduce:**
1. Open sandbox: https://stackblitz.com/edit/vitejs-vite-7cd1nv?file=src%2FApp.tsx
2. run `npx tsc --noEmit`
4.  Catch TS Error:
```
src/App.tsx:26:8 - error TS2786: 'DataLoaderBase' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.

26       <DataLoaderBase
          ~~~~~~~~~~~~~~

Found 1 error in src/App.tsx:26
````

**Comment by DakEnviy** [comment]
This error appears when using Typescript version 5.0.4 and below. It was fixed in version 5.1.3
https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#linked-cursors-for-jsx-tags
